name: Fetch Equity Futures Data via cURL

on:
  repository_dispatch:
  workflow_dispatch:  # Allows manual trigger

jobs:
  fetch-futures-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Futures Data Using cURL
        id: future
        env:
          KITE_API_KEY: ${{ secrets.API_KEY }}
          KITE_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          # Define stock and futures pairs
          STOCKS=("NSE:ANGELONE" "NSE:IREDA" "NSE:CAMS" "NSE:TATAELXSI" "NSE:TATATECH" "NSE:SONACOMS" "NSE:AUBANK")
          FUTURES=("NFO:ANGELONE25MAYFUT" "NFO:IREDA25MAYFUT" "NFO:CAMS25MAYFUT" "NFO:TATAELXSI25MAYFUT" "NFO:TATATECH25MAYFUT" "NFO:SONACOMS25MAYFUT" "NFO:AUBANK25MAYFUT")
      
          # Initialize error message variable
          ERROR_MESSAGE=""
      
          # Construct API query dynamically
          SYMBOLS_QUERY=""
          for ((i=0; i<${#STOCKS[@]}; i++)); do
            SYMBOLS_QUERY+="&i=${STOCKS[i]}&i=${FUTURES[i]}"
          done
          API_URL="https://api.kite.trade/quote/ltp?${SYMBOLS_QUERY}"
      
          # Make the API request
          RESPONSE=$(curl -s -X GET "$API_URL" \
            -H "X-Kite-Version: 3" \
            -H "Authorization: token $KITE_API_KEY:$KITE_ACCESS_TOKEN")
      
          echo "Response: $RESPONSE"
      
          # Process each stock-future pair
          for ((i=0; i<${#STOCKS[@]}; i++)); do
            STOCK=${STOCKS[i]}
            FUTURE=${FUTURES[i]}
      
            DIFFERENCE=$(echo "$RESPONSE" | jq --arg stock "$STOCK" --arg future "$FUTURE" '(.data[$stock].last_price - .data[$future].last_price)')
            echo "Difference between $STOCK and $FUTURE: $DIFFERENCE"
      
            # Define threshold checks
            if [[ "$STOCK" == "NSE:TATATECH" && $(echo "$DIFFERENCE <= 30" | bc -l) -eq 1 ]]; then
              ERROR_MESSAGE+="Error: The price difference for TATATECH below $DIFFERENCE!\n"
            fi       

             # Define threshold checks
            if [[ "$STOCK" == "NSE:TATATECH" && $(echo "$DIFFERENCE >= 33" | bc -l) -eq 1 ]]; then
              ERROR_MESSAGE+="Error: The price difference for TATATECH exceeds $DIFFERENCE!\n"
            fi     

            if [[ "$STOCK" == "NSE:TATAELXSI" && $(echo "$DIFFERENCE >= 120" | bc -l) -eq 1 ]]; then
              ERROR_MESSAGE+="Error: The price difference for TATAELXSI exceeds $DIFFERENCE!\n"
            fi  

             if [[ "$STOCK" == "NSE:TATAELXSI" && $(echo "$DIFFERENCE <= 90" | bc -l) -eq 1 ]]; then
              ERROR_MESSAGE+="Error: The price difference for TATAELXSI below $DIFFERENCE!\n"
            fi  
             if [[ "$STOCK" == "NSE:SONACOMS" && $(echo "$DIFFERENCE <= 16" | bc -l) -eq 1 ]]; then
             ERROR_MESSAGE+="Error: The price difference for SONACOMS below $DIFFERENCE!\n"
            fi 
             if [[ "$STOCK" == "NSE:SONACOMS" && $(echo "$DIFFERENCE >= 20" | bc -l) -eq 1 ]]; then
             ERROR_MESSAGE+="Error: The price difference for SONACOMS below $DIFFERENCE!\n"
            fi             
             if [[ "$STOCK" == "NSE:AUBANK" && $(echo "$DIFFERENCE <= 11" | bc -l) -eq 1 ]]; then
             ERROR_MESSAGE+="Error: The price difference for AUBANK below $DIFFERENCE!\n"
            fi            
             if [[ "$STOCK" == "NSE:AUBANK" && $(echo "$DIFFERENCE >= 13" | bc -l) -eq 1 ]]; then
             ERROR_MESSAGE+="Error: The price difference for AUBANK below $DIFFERENCE!\n"
            fi  
         
      
           

            
           

            
          done
      
          # Set the ERROR_MESSAGE as an environment variable for subsequent steps
          echo "ERROR_MESSAGE<<EOF" >> $GITHUB_ENV
          echo -e "$ERROR_MESSAGE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      
          # Check if there were any errors and exit if so
          if [[ -n "$ERROR_MESSAGE" ]]; then
            echo -e "$ERROR_MESSAGE"
            exit 1
          fi

      - name: send message to whatsapp
        if: failure()
        run: |
          curl -X POST "https://api.twilio.com/2010-04-01/Accounts/${{ secrets.TWILIO_ACCOUNT_SID }}/Messages.json" \
          --data-urlencode "Body=${{env.ERROR_MESSAGE}}" \
          --data-urlencode "From=whatsapp:${{ secrets.TWILIO_WHATSAPP_NUMBER }}" \
          --data-urlencode "To=whatsapp:${{ secrets.TO_WHATSAPP_NUMBER }}" \
          -u "${{ secrets.TWILIO_ACCOUNT_SID }}:${{ secrets.TWILIO_AUTH_TOKEN }}"


      - name: Dispatch Slack notification
        if: failure()
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            {
              "channel": "${{ secrets.SLACK_CHANNEL_ID }}",
              "text": "${{env.ERROR_MESSAGE}}",
              "attachments": [
                {
                  "title": "Scheduled Job Status: Failed",
                  "fields": [
                    {
                      "title": "Link to Latest Job",
                      "value": "https://github.com/TrailheadTechOps/DRM-TA-UCS/actions/runs/${{ env.run_id }}",
                      "short": false
                    }
                  ]
                }
              ]
            }
