name: Fetch Equity Futures Data via cURL

on:
  repository_dispatch:
  workflow_dispatch:  # Allows manual trigger

jobs:
  fetch-futures-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Futures Data Using cURL
        id: future
        env:
          KITE_API_KEY: ${{ secrets.API_KEY }}
          KITE_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          # Define stock and futures pairs
          STOCKS=("NSE:ANGELONE" "NSE:IREDA" "NSE:TCS")
          FUTURES=("NFO:ANGELONE25APRFUT" "NFO:IREDA25APRFUT" "NFO:TCS25MARFUT")
      
          # Construct API query dynamically
          SYMBOLS_QUERY=""
          for ((i=0; i<${#STOCKS[@]}; i++)); do
            SYMBOLS_QUERY+="&i=${STOCKS[i]}&i=${FUTURES[i]}"
          done
          API_URL="https://api.kite.trade/quote/ltp?${SYMBOLS_QUERY}"  
          
          # Make the API request
          RESPONSE=$(curl -s -X GET "$API_URL" \
            -H "X-Kite-Version: 3" \
            -H "Authorization: token $KITE_API_KEY:$KITE_ACCESS_TOKEN")
          
          echo "Response: $RESPONSE"
          
          # Process each stock-future pair
          for ((i=0; i<${#STOCKS[@]}; i++)); do
            STOCK=${STOCKS[i]}
            FUTURE=${FUTURES[i]}
            
            DIFFERENCE=$(echo "$RESPONSE" | jq --arg stock "$STOCK" --arg future "$FUTURE" '(.data[$stock].last_price - .data[$future].last_price)')
            echo "Difference between $STOCK and $FUTURE: $DIFFERENCE"
            
            # Define threshold checks
            if [[ "$STOCK" == "NSE:ANGELONE" && $(echo "$DIFFERENCE <= 115" | bc -l) -eq 1 ]]; then
              echo "Error: The price difference for ANGELONE exceeds 115!"
              exit 1
            fi

             if [[ "$STOCK" == "NSE:ANGELONE" && $(echo "$DIFFERENCE >= 125" | bc -l) -eq 1 ]]; then
              echo "Error: The price difference for ANGELONE exceeds 140!"
              exit 1
            fi
            
            if [[ "$STOCK" == "NSE:IREDA" && $(echo "$DIFFERENCE <= 11" | bc -l) -eq 1 ]]; then
              echo "Error: The price difference for IREDA is less than 10.50!"
              exit 1
            fi
      
            if [[ "$STOCK" == "NSE:IREDA" && $(echo "$DIFFERENCE >= 13.50" | bc -l) -eq 1 ]]; then
              echo "Error: The price difference for IREDA is greater than 11.50!"
              exit 1
            fi
          done
  
      - name: send message to whatsapp
        if: failure()
        run: |
          curl -X POST "https://api.twilio.com/2010-04-01/Accounts/${{ secrets.TWILIO_ACCOUNT_SID }}/Messages.json" \
          --data-urlencode "Body=arbitrage opportunity!" \
          --data-urlencode "From=whatsapp:${{ secrets.TWILIO_WHATSAPP_NUMBER }}" \
          --data-urlencode "To=whatsapp:${{ secrets.TO_WHATSAPP_NUMBER }}" \
          -u "${{ secrets.TWILIO_ACCOUNT_SID }}:${{ secrets.TWILIO_AUTH_TOKEN }}"
