name: Fetch 1-Minute Close Prices

on:
  schedule:
    - cron: "5 10 * * 1-5" # Runs at 3:35 PM IST (10:05 AM UTC)
  workflow_dispatch: # Allows manual trigger

jobs:
  fetch_minute_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install requests pandas

      - name: Fetch 1-Minute Data
        env:
          KITE_API_KEY: ${{ secrets.KITE_API_KEY }}
          KITE_ACCESS_TOKEN: ${{ secrets.KITE_ACCESS_TOKEN }}
        run: |
          python fetch_minute_data.py

      - name: Upload CSV as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: minute-data
          path: minute_data_today.csv
